{% set name = "tikzplotlib" %}
{% set version = "0.8.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2cf9ec0d71be242c830f7216c53c6fb8c9d1ed9dadcac1315f64176a8893cbdf

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - matplotlib >=1.4.0
    - numpy
    - pillow

test:
  imports:
    - tikzplotlib

about:
  home: https://github.com/nschloe/tikzplotlib
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Convert matplotlib figures into TikZ/PGFPlots'
  dev_url: https://github.com/nschloe/tikzplotlib

extra:
  recipe-maintainers:
    - m-rossi
