{% set name = "tikzplotlib" %}
{% set version = "0.8.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 601f9e1ab3b60d1508d04216ee6731327b58af0a15ae730bcf27d390c090e789

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - matplotlib >=1.4.0
    - numpy
    - pillow

test:
  imports:
    - tikzplotlib
    - tikzplotlib.axes
    - tikzplotlib.color
    - tikzplotlib.files
    - tikzplotlib.image
    - tikzplotlib.legend
    - tikzplotlib.line2d
    - tikzplotlib.patch
    - tikzplotlib.path
    - tikzplotlib.quadmesh
    - tikzplotlib.save
    - tikzplotlib.text
    - tikzplotlib.util

about:
  home: https://github.com/nschloe/tikzplotlib
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Convert matplotlib figures into TikZ/PGFPlots'
  dev_url: https://github.com/nschloe/tikzplotlib

extra:
  recipe-maintainers:
    - m-rossi
