{% set name = "tikzplotlib" %}
{% set version = "0.9.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1eaabe1d862664759520fc2cddcab39fd80c3aae95607095dac1ee372b4417d2

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools >=42.0
    - wheel
  run:
    - importlib_metadata
    - python >=3.6
    - matplotlib-base >=1.4.0
    - numpy
    - pillow

test:
  imports:
    - tikzplotlib

about:
  home: https://github.com/nschloe/tikzplotlib
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Convert matplotlib figures into TikZ/PGFPlots
  dev_url: https://github.com/nschloe/tikzplotlib

extra:
  recipe-maintainers:
    - m-rossi
