travis:
  secure:
    BINSTAR_TOKEN: Wg5vGirLRUuZh47Ozc7AAOwBesyqPJCPQpYsBPPQet7u9d9J8t+w/hkUIwmp8St0pgQmcMPc8YeoY2znFPQw2AeWIe+3O6LPHTJ7YZ3YWxheZ8tgVUgANXH6t9GfB7AmLOdBcnbZbm0ORuqGYUjOMaiwjBJ1MFgcF29cSmxIs4oZ/W7Y3FnjW5b9RSd1CPp88gUaJ1wRxwvaNChTlNY9nvIT9LGvrNNxYWnK0dbiwE8zL7bHlBKUfsQNzbiK41BuvHNpvSNyhNCyo6BXzTGCVwl7D2b5cnswDKiiNBq+DVCicqvVdo+dTxovX287GwINxsQd4bqEFk+kGG0ECOfQT/I2Hlr+BM9K1jfqNDCn5iehcojcJSzjFQgAPKzy+ChF+MJ60dk6X2XpqVjE34lOjNcN/EEZ6+KbM53He4hezvXPMYdrFMuXCP9K2nvQ5KbQFkSaudWjPcHnHR1OINa4S8fGYRQdNnllb+Mxb6xOG6S+aovOkudLAFZbnEXc0jUcFIm1rHZ9O6zrh5T2he531AQd3LTh7xk4dRcJBk7jkY/PnJSvry/5tYnAgY7102yVKDAM0+VKcc4SC9jX8XKxorVwVfn8Kgk3keV1U4ODSG3XLbp/0dJeofXybQWIHWtL+E03cc58tyVyiDW2QJgdTbGi3Aom1trmuGHGoFircUY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
